name: Draft PDF

on:
  push:
    branches:
      - pdf-subs
permissions:
  contents: read

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        env:
          JOURNAL: joss
          GIT_SHA: ${{ github.sha }}
        run: |
          docker run --rm \
            -e JOURNAL="${JOURNAL}" \
            -e GIT_SHA="${GIT_SHA}" \
            -v "${GITHUB_WORKSPACE}:/github/workspace" \
            -w /github/workspace \
            openjournals/inara:latest \
            -o pdf paper/paper.md
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf
